# Generated by Django 4.2.9 on 2024-05-27 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_remove_order_products_alter_order_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_cancelled',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
