# Generated by Django 4.2.9 on 2024-05-27 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_alter_order_is_cancelled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='is_cancelled',
            new_name='order_status',
        ),
    ]
